###
POST http://localhost:3000/api/Account/Register
Content-Type: application/json

{
  "Username": "testuser2342",
  "Password": "securepassword123"
}

###
POST http://localhost:3000/api/Account/Login
Content-Type: application/json

{
  "Username": "testuser4",
  "Password": "securepassword123"
}
