###
POST http://localhost:5000/api/Account/Register
Content-Type: application/json

{
  "Username": "testuser234222",
  "Password": "securepassword123"
}

###
POST http://localhost:5000/api/Account/Login
Content-Type: application/json

{
  "Username": "testuser4",
  "Password": "securepassword123"
}
